name: LearnGo

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Cache Docker Image Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/learngo
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: docker 
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/learngo:latest
      - name: Delete old container
        run: docker rm -f learngo
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name learngo -e MONGO_URL=${{ secrets.MONGO_URL }} -e PORT=${{ secrets.PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/learngo
