name: LearnGo

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and Push DockerFile
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          cd src/
          sudo docker build -t thaily/learngo .
          sudo docker push thaily/learngo
  deploy:
    needs: docker 
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/learngo:latest
      - name: Delete old container
        run: docker rm -f learngo
      - name: Run docker container
        run: docker run -d -p 8080:8082 --name learngo -e MONGO_URL=${{ secrets.MONGO_URL }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e YOUR_CLIENT_ID=${{ secrets.YOUR_CLIENT_ID }} -e PORT=${{ secrets.PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/learngo
